# You can call this workflow file from another workflow file.
name: 'Validate bicep file'
on:
  workflow_call:
    inputs:
      # Files and directories that a reusable workflow requires to run
      # should be passed to it using an artifact.
      files_artifact:
        required: false
        type: string
      bicep_file:
        required: true
        type: string
      bicep_params_file:
        required: false
        type: string

jobs:
  azure-login-job:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{secrets.AZURE_CLIENT_ID}}
        tenant-id: ${{secrets.AZURE_TENANT_ID}}
        subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

  lint-bicep-job:
    runs-on: ubuntu-latest
    needs: azure-login-job
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{inputs.files_artifact}}
    - name: 'Run Bicep linter'
      uses: azure/CLI@v1 token
      id: bicep-linter
      with:
          inlineScript: |
              az bicep build --file {{inputs.bicep_file}} 

  validate-bicep-job:
    runs-on: ubuntu-latest
    needs: azure-login-job
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{inputs.files_artifact}}
    - name: 'Validate the Azure infrastructure using Bicep'
      # See https://github.com/marketplace/actions/deploy-azure-resource-manager-arm-template
      uses: azure/arm-deploy@v1
      id: validate_bicep
      with:
        scope: resourcegroup
        subscriptionId: ${{secrets.AZURE_SUBSCRIPTION_ID}}
        resourceGroupName: ${{vars.AZURE_DEPLOYMENT_RG}}
        template: ${{inputs.bicep_file}}
        parameters: ${{inputs.bicep_params_file}}
        deploymentName: validateInfrastructureDeployment
        deploymentMode: 'Validate'

  preview-bicep-job:
    runs-on: ubuntu-latest
    needs: [azure-login-job, lint-bicep-job, validate-bicep-job]  # This job depends on the lint and validate jobs
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{inputs.files_artifact}}
    - name: 'Preview the Azure infrastructure using Bicep'
      uses: azure/arm-deploy@v1
      id: preview_bicep
      with:
        scope: resourcegroup
        subscriptionId: ${{secrets.AZURE_SUBSCRIPTION_ID}}
        resourceGroupName: ${{vars.AZURE_DEPLOYMENT_RG}}
        template: ${{inputs.bicep_file}}
        parameters: ${{inputs.bicep_params_file}}
        deploymentName: previewInfrastructureDeployment
        additionalArguments: '--what-if'